build: update cython to version 0.29.36
This is needed to avoid this compilation error with newer Python
versions:

```
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -g0 -fPIC -I/opt/electroncash/contrib/build-linux/appimage/build/appimage/Electron-Cash.AppDir/usr/include/python3.11 -c /tmp/pip-install-e6h0s5ra/cython_2dbbde4fa5f84fe58fe0c46b2f1146ba/Cython/Plex/Scanners.c -o build/temp.linux-x86_64-3.11/tmp/pip-install-e6h0s5ra/cython_2dbbde4fa5f84fe58fe0c46b2f1146ba/Cython/Plex/Scanners.o
/tmp/pip-install-e6h0s5ra/cython_2dbbde4fa5f84fe58fe0c46b2f1146ba/Cython/Plex/Scanners.c:211:12: fatal error: longintrepr.h: No such file or directory
      211 |   #include "longintrepr.h"
      |            ^~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
[end of output]
```