build: update psutil to version 5.9.5
This is needed because the Windows build currently does not have working
development headers installed, but the newer version has wheels for
Python 3.11 so doesn't need compilation.

```
C:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERS
ION=580 -DPSUTIL_WINDOWS=1 -D_WIN32_WINNT=0x0601 -D_AVAIL_WINVER_=0x0601 -D_CRT_SECURE_NO_WARNINGS -DPSAPI_VERSION=1 -IC:\python3.11.6\include -IC:\python3.11.6\Include -IC:\Program Fil
es\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files\Windows Kits\10\include\10.0
.19041.0\shared -IC:\Program Files\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files\Windows Kits\10\include\10.0.
19041.0\cppwinrt /Tcpsutil/_psutil_common.c /Fobuild\temp.win32-3.11\Release\psutil/_psutil_common.obj
_psutil_common.c
psutil/_psutil_common.c(9): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x86\\cl.exe' failed with exit code 2
[end of output]
```