build: update pycryptodomex to version 3.19.0
This is needed because the Windows build currently does not have working
development headers installed, but the newer version has wheels for
Python 3.11 so doesn't need compilation.

```
C:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DHAVE_STDINT_H -DPYCRYPTO_LITTLE_END
IAN -DSYS_BITS=32 -DLTC_NO_ASM -DHAVE_INTRIN_H -DHAVE_INTRIN_H -DUSE_SSE2 -Isrc/ -IC:\python3.11.6\include -IC:\python3.11.6\Include -IC:\Program Files\Microsoft Visual Studio\2019\Buil
dTools\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files\W
indows Kits\10\include\10.0.19041.0\um -IC:\Program Files\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tcsrc/MD2.c /Fobui
ld\temp.win32-3.11\Release\src/MD2.obj
MD2.c
C:\users\user\Temp\pip-install-r8upie9g\pycryptodomex_a40f655965f94699af69acaf6f58cf79\src\common.h(113): fatal error C1083: Cannot open include file: 'Python.h': No such file or
directory
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x86\\cl.exe' failed with exit code 2
[end of output]
```