build: update cffi to version 1.16.0
This is needed because the Windows build currently does not have working
development headers installed, but the newer version has wheels for
Python 3.11 so doesn't need compilation.

```
C:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic/libffi_msvc -IC:\python3.11.6\inc
lude -IC:\python3.11.6\Include -IC:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files\Windows Kits\10\include\10.0.19041.0\ucrt
-IC:\Program Files\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files\Windows Kits\10\include\10.0.19041.0\winrt -
IC:\Program Files\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tcc/_cffi_backend.c /Fobuild\temp.win32-3.11\Release\c/_cffi_backend.obj
_cffi_backend.c
c/_cffi_backend.c(2): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x86\\cl.exe' failed with exit code 2
[end of output]
```