Qt: Fix PyQt5 import from PyQt5.Qt instead of PyQt5.QtCore
The `PyQt5.Qt` namespace should not be used.

```
ImportError: cannot import name 'Qt' from 'PyQt5.Qt' (unknown location)
```