build: constrain cython for hidapi build in wine
https://github.com/trezor/cython-hidapi/issues/155
https://github.com/trezor/cython-hidapi/pull/159
https://github.com/trezor/cython-hidapi/commit/749da6931f57c4c30596de678125648ccfd6e1cd#commitcomment-122264301

```
 error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running bdist_wheel
      running build
      running build_ext
      c:\users\user\temp\pip-install-5h0utb8j\hidapi_8e4b6425e91e4c8db312715d87ffd81a\.eggs\cython-3.0.3-py3.11-win32.egg\Cython\Compiler\Main.py:381: FutureWarning: Cython directive 'l
anguage_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\users\user\Temp\pip-install-5h0utb8j\hidapi_8e4b6425e91e4c8db312715d87ffd81a\hid.pyx

        tree = Parsing.p_module(s, pxd, full_module_name)
      Compiling hid.pyx because it changed.
      [1/1] Cythonizing hid.pyx
      building 'hid' extension
      error: Don't know how to compile chid.pxd
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hidapi
  Running setup.py clean for hidapi
  Building wheel for pyscard (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'smartcard.scard._scard' extension
      swigging smartcard/scard/scard.i to smartcard/scard/scard_wrap.c
      swig.exe -python -outdir smartcard/scard -DWIN32 -o smartcard/scard/scard_wrap.c smartcard/scard/scard.i
      error: command 'swig.exe' failed: None
      [end of output]
```